/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AlliCard {
    }
}
declare global {
    interface HTMLAlliCardElement extends Components.AlliCard, HTMLStencilElement {
    }
    var HTMLAlliCardElement: {
        prototype: HTMLAlliCardElement;
        new (): HTMLAlliCardElement;
    };
    interface HTMLElementTagNameMap {
        "alli-card": HTMLAlliCardElement;
    }
}
declare namespace LocalJSX {
    interface AlliCard {
    }
    interface IntrinsicElements {
        "alli-card": AlliCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "alli-card": LocalJSX.AlliCard & JSXBase.HTMLAttributes<HTMLAlliCardElement>;
        }
    }
}
